### ISSUE TITLE
How do you get the carrier?

### ISSUE THREAD

**Issue by davidtlee** [preston/sms-easy#3]
Hi Preston,

Thanks for writing this gem! I was wondering, how do you get the carrier from a phone (on the javascript side)? Basically, what I want to do is to just ask the user to input their phone number rather than having to input both their phone number and carrier. Is there an example you can point to of using this gem that I could reference?

Thanks!
David

**Comment by preston** [comment]
Good question, but no clue. I'm doubtful that it's even possible. :-/

**Comment by davidtlee** [comment]
I see... so in your implementation, do you just ask the user to input their carrier then?

**Comment by preston** [comment]
Yup. That's the only way I'm aware of.
