### ISSUE TITLE
Cannot require sms-easy gem from a ruby script

### ISSUE THREAD

**Issue by TamimiGitHub** [preston/sms-easy#8]
Upon attempting to require the sms-easy gem into my ruby script I get the following issues

`.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sms-easy-1.3.3/lib/sms/easy/easy.rb:5:in `<class:Client>': private method `load' called for Psych:Module (NoMethodError)`

and this is how I am requiring it 
```
require 'rubygems'
require 'sms-easy'
```

Any assistance with this is greatly appreciate it

**Comment by TamimiGitHub** [comment]
I found the issue. I had to `gem install psych -v 2.0.6` as it only works with this version

**Comment by preston** [comment]
Interesting -- thank you!
